spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
      username: sa
      password: password
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        #show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
